import type { Metadata } from "next";
import "./globals.css";
import { SWRProvider } from "@/components/SWRProvider";

export const metadata: Metadata = {
  title: "Job Prospects",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Jacquard+12&family=Press+Start+2P&family=Jersey+10&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="h-full">
        <SWRProvider>{children}</SWRProvider>
      </body>
    </html>
  );
}
