import type { Metadata } from "next";
import "./globals.css";
import { SWRProvider } from "@/components/SWRProvider";

export const metadata: Metadata = {
  title: "Job Prospects",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full">
        <SWRProvider>{children}</SWRProvider>
      </body>
    </html>
  );
}
